apply plugin: 'java'
apply plugin: 'application'

repositories {
    mavenCentral()
}

dependencies {
    // Selenium (required)
    compile 'org.seleniumhq.selenium:selenium-java:4.21.0'

    // FIX: Auto driver management (VERY IMPORTANT)
    compile 'io.github.bonigarcia:webdrivermanager:5.8.0'

    // Guava
    compile 'com.google.guava:guava:23.0'

    // JUnit
    testCompile 'junit:junit:4.12'
}

// IMPORTANT for old Gradle versions
mainClassName = 'App'

task display {
    doLast {
        println "Good Morning its a devops class"
    }
}
