plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'

    // WebDriverManager
    implementation 'io.github.bonigarcia:webdrivermanager:5.8.0'

    // Guava
    implementation 'com.google.guava:guava:23.0'

    // JUnit
    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'App'
}

task display {
    doLast {
        println "Good Morning its a devops class"
    }
}
